spring:
   datasource:
      username: numerology_calendar
      password: numerology_calendar
      url: jdbc:mysql://localhost:3306/numerology_calendar
   
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true
   
   sql:
      init:
         mode: always